### ISSUE TITLE
Local Storage is cleared on refresh if auth State is not set on signIn.

### ISSUE THREAD

**Issue by dgtlntv** [react-auth-kit/react-auth-kit#876]
**Describe the bug**
I have the AuthProvider set to local storage. If I don't set authState on signIn (even though it should be optional) the local storage is cleared on page refresh and thus the user is being logged out.

**To Reproduce**
Have AuthProvider set to localstorage and dont set authState on signIn.

My AuthProvider:
```javascript
import Routing from "./components/Routing"
import { AuthProvider } from "react-auth-kit";
import { QueryClient, QueryClientProvider } from "react-query";

const queryClient = new QueryClient()

const App = function() {
    return (
        <QueryClientProvider client={ queryClient }>
            <AuthProvider authType="localstorage" authName="_auth">
                <Routing />
            </AuthProvider>
        </QueryClientProvider>
    );
}

export default App;

```

My Login Hook:
```javascript
import { useSignIn } from "react-auth-kit";
import { useNavigate } from "react-router-dom";
import fetchData from "../../services/fetchData.service";

export const useLogin = function() {
    const signIn = useSignIn()
    const navigate = useNavigate();

    return function login(email, password) {
        const requestOptions = {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: JSON.stringify(`grant_type=&username=${email}&password=${password}&scope=&client_id=&client_secret=`),
        };

        fetchData(`/auth/token`, requestOptions)
        .then(function(res) {
            signIn({
                token: res.access_token,
                expiresIn: res.expires_in,
                tokenType: res.token_type,

                // if I don't set authState here localstorage is cleared on page refresh
                // authState: res.auth_state,
            })
            navigate("/");
        })
        .catch(function(error) {
            console.log("Login failed", error);
        });
    }
};
```

**Comment by darkmatter18** [comment]
Let me check te issue, if I find anything I'll inform you.

**Comment by faner11** [comment]
I also encountered this problem

**Comment by darkmatter18** [comment]
@faner11 Can you explain the issue in detail, like when you are getting the issue?

**Comment by aram0112** [comment]
I figured out the issue in my case, the authentication flow in my application has the auth token put directly in the Authorization header, hence I was leaving the auth token type blank so that the useAuthHeader would not put anything in front of the token, however the initialLSToken function checks that Auth Type is not blank and otherwise does not populate the previous state. After putting a value for tokenType it is not clearing the localStorage

**Comment by faner11** [comment]
@darkmatter18 The reason is found, I did not set the authState field

**Comment by ubmarco** [comment]
First, thanks for this helpful library!
I have the same issue and I think the issue should not be in a closed state.
Setting `authState` to an arbitrary value makes page refresh persist the local storage. It is deleted otherwise.
Here are the docs:
![image](https://user-images.githubusercontent.com/839934/177212086-78ec2d25-5128-4a2b-b036-56acc2b1bbee.png)
It says `authState` is optional. Either the docs need an update or the implementation.

**Comment by gabohc** [comment]
Short answer: set `authState: {}` and it will work.
